language: python
env:
  - JYTHON=true
  - JYTHON=false

virtualenv:
  system_site_packages: true

install: ./.travis_prepare.sh

before_script:
    - if [ "$JYTHON" == "true" ]; then export PYTHON_EXE="$HOME/jython/jython -J-Djava.library.path=/usr/lib/jni -J-Xmx2048M"; else export PYTHON_EXE=python; fi
    - if [ "$JYTHON" == "true" ]; then export JYTHONPATH="/usr/share/java/glpk-java.jar:$HOME/jsbml-0.8-with-dependencies.jar"; fi
    - $PYTHON_EXE -c "print ''"

script: $PYTHON_EXE setup.py test
