language: python
env:
  - JYTHON=true
  - JYTHON=false

# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
  - if [ "$JYTHON" == "false" ]; then sudo apt-get install libglpk-dev python-scipy libgmp-dev; fi
  - cd /home/travis
  - wget http://clostridium.ucsd.edu/libsbml-5.6.0_built_with_py.tar.gz
  - tar xzf libsbml-5.6.0_built_with_py.tar.gz
  - cd libsbml-5.6.0/
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - if [ "$JYTHON" == "true" ]; then sudo apt-get install libglpk-java; fi
  - if [ "$JYTHON" == "true" ]; then wget http://clostridium.ucsd.edu/jython-installer-2.7-b1.jar; fi
  - if [ "$JYTHON" == "true" ]; then java -jar jython-installer-2.7-b1.jar -s -d $HOME/jython; fi
  - if [ "$JYTHON" == "true" ]; then export PYTHON_EXE=$HOME/jython/jython; $PYTHON_EXE -c "print ''"; else export PYTHON_EXE=python; fi

install:
  - ln -s /usr/lib/python2.7/dist-packages/scipy ~/virtualenv/python2.7/lib/python2.7/site-packages/
  - if [ "$JYTHON" == "false" ]; then pip install glpk; fi
# # command to run tests
script: $PYTHON_EXE setup.py test
